// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.EF.Api.EFContext;

#nullable disable

namespace Project.EF.Api.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20251122015847_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.EF.Api.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca89d"),
                            Name = "Pending Activities",
                            Weight = 50
                        },
                        new
                        {
                            CategoryId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca891"),
                            Name = "Personal Activities",
                            Weight = 60
                        });
                });

            modelBuilder.Entity("Project.EF.Api.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TareaPriority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca810"),
                            CategoryId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca89d"),
                            CreationDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            TareaPriority = 2,
                            Title = "Renew car insurance"
                        },
                        new
                        {
                            TareaId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca811"),
                            CategoryId = new Guid("e29765db-6368-49b3-9a97-88f8be1ca891"),
                            CreationDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            TareaPriority = 0,
                            Title = "Watch anime"
                        });
                });

            modelBuilder.Entity("Project.EF.Api.Models.Tarea", b =>
                {
                    b.HasOne("Project.EF.Api.Models.Category", "Category")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project.EF.Api.Models.Category", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
